name: Fibnoacci Series workflow.
on: push

jobs:
  build:
    name: Run the Fibnoacci action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./fib
        with:
          N_INDEX: 12
